version="0.3.1"

[scripts]
## Runs Eleventy for development (assuming Tailwind is ready after `setup`)
dev = "eleventy --serve"
## Builds everything for production (the result of this will be served live)
build = [
    "bonnie build-tailwind-prod",
    "ELEVENTY_PRODUCTION=true eleventy"
]

## Builds Tailwind CSS for development (no purging)
build-tailwind-dev = "tailwindcss -c ./src/styles/tailwind.config.js -o ./_tmp/tailwind.css"
## Builds Tailwind CSS for production (maximum purging and minification)
build-tailwind-prod = "NODE_ENV=production tailwindcss -c ./src/styles/tailwind.config.js -o ./_tmp/tailwind.css --minify"

## Builds Tailwind CSS for development usage
setup.subcommands.tailwind = "bonnie build-tailwind-dev"
setup.subcommands.prompt-tailwind = "echo \"Have you installed the Tailwind CLI globally with 'npm i -g tailwindcss' or 'yarn global add tailwindcss'?\""
## Tells the user if an error occurs
setup.subcommands.error = "echo \"An error occurred in the setup process. This shouldn't happen, so please report it as a bug.\""
setup.order = """
tailwind {
    Failure => prompt-tailwind
}
"""
