name: Build and Publish Site
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install packages
              run: yarn
            - name: Build site
              run: NODE_ENV=production yarn postcss "src/styles/**/*.css" -o ./_tmp/style.css && ELEVENTY_PRODUCTION=true yarn eleventy
            - name: Deploy site to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist
